"""initial schema

Revision ID: 2c0072fd6670
Revises: 
Create Date: 2026-08-11 14:57:12.127513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c0072fd6670'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_code'), 'roles', ['code'], unique=True)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_vacant', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_department_id'), 'positions', ['department_id'], unique=False)
    op.create_index(op.f('ix_positions_title'), 'positions', ['title'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender', native_enum=False, length=10), nullable=False),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('citizenship', sa.String(length=100), nullable=True),
    sa.Column('marital_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', name='maritalstatus', native_enum=False, length=20), nullable=True),
    sa.Column('academic_degree', sa.String(length=150), nullable=True),
    sa.Column('academic_title', sa.String(length=150), nullable=True),
    sa.Column('foreign_languages', sa.String(length=255), nullable=True),
    sa.Column('military_rank', sa.String(length=150), nullable=True),
    sa.Column('party_affiliation', sa.String(length=150), nullable=True),
    sa.Column('public_office_note', sa.Text(), nullable=True),
    sa.Column('pinfl_encrypted', sa.String(length=512), nullable=True),
    sa.Column('pinfl_hash', sa.String(length=64), nullable=True),
    sa.Column('passport_series', sa.String(length=4), nullable=True),
    sa.Column('passport_number_encrypted', sa.String(length=512), nullable=True),
    sa.Column('passport_issued_by', sa.String(length=255), nullable=True),
    sa.Column('passport_issued_date', sa.Date(), nullable=True),
    sa.Column('current_address', sa.String(length=500), nullable=True),
    sa.Column('permanent_address', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('photo_path', sa.String(length=500), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('position_since', sa.Date(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('employment_status', sa.Enum('ACTIVE', 'ON_LEAVE', 'DISMISSED', name='employmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('specialization_area', sa.String(length=100), nullable=True),
    sa.Column('positive_traits', sa.Text(), nullable=True),
    sa.Column('negative_traits', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_employment_status'), 'employees', ['employment_status'], unique=False)
    op.create_index(op.f('ix_employees_first_name'), 'employees', ['first_name'], unique=False)
    op.create_index('ix_employees_fullname_trgm', 'employees', ['last_name', 'first_name', 'middle_name'], unique=False, postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops', 'first_name': 'gin_trgm_ops', 'middle_name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_employees_is_deleted'), 'employees', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employees_last_name'), 'employees', ['last_name'], unique=False)
    op.create_index(op.f('ix_employees_pinfl_hash'), 'employees', ['pinfl_hash'], unique=True)
    op.create_index(op.f('ix_employees_position_id'), 'employees', ['position_id'], unique=False)
    op.create_index(op.f('ix_employees_position_since'), 'employees', ['position_since'], unique=False)
    op.create_index(op.f('ix_employees_specialization_area'), 'employees', ['specialization_area'], unique=False)
    op.create_table('awards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('awarded_date', sa.Date(), nullable=False),
    sa.Column('recommending_organization', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_awards_employee_id'), 'awards', ['employee_id'], unique=False)
    op.create_table('education_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=False),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Enum('SECONDARY', 'SECONDARY_SPECIAL', 'BACHELOR', 'MASTER', 'PHD', name='educationlevel', native_enum=False, length=30), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_education_history_employee_id'), 'education_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_education_history_specialty'), 'education_history', ['specialty'], unique=False)
    op.create_table('foreign_trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('order_basis', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foreign_trips_employee_id'), 'foreign_trips', ['employee_id'], unique=False)
    op.create_table('relatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.Enum('FATHER', 'MOTHER', 'SPOUSE', 'CHILD', 'SIBLING', 'OTHER', name='relativetype', native_enum=False, length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('birth_place', sa.String(length=255), nullable=True),
    sa.Column('workplace', sa.String(length=255), nullable=True),
    sa.Column('position_title', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relatives_employee_id'), 'relatives', ['employee_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secret_encrypted', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('order_reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_history_employee_id'), 'work_history', ['employee_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_record_id'), 'audit_logs', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('document_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_attachments_employee_id'), 'document_attachments', ['employee_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_attachments_employee_id'), table_name='document_attachments')
    op.drop_table('document_attachments')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_table_name'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_record_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_work_history_employee_id'), table_name='work_history')
    op.drop_table('work_history')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_relatives_employee_id'), table_name='relatives')
    op.drop_table('relatives')
    op.drop_index(op.f('ix_foreign_trips_employee_id'), table_name='foreign_trips')
    op.drop_table('foreign_trips')
    op.drop_index(op.f('ix_education_history_specialty'), table_name='education_history')
    op.drop_index(op.f('ix_education_history_employee_id'), table_name='education_history')
    op.drop_table('education_history')
    op.drop_index(op.f('ix_awards_employee_id'), table_name='awards')
    op.drop_table('awards')
    op.drop_index(op.f('ix_employees_specialization_area'), table_name='employees')
    op.drop_index(op.f('ix_employees_position_since'), table_name='employees')
    op.drop_index(op.f('ix_employees_position_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_pinfl_hash'), table_name='employees')
    op.drop_index(op.f('ix_employees_last_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_is_deleted'), table_name='employees')
    op.drop_index('ix_employees_fullname_trgm', table_name='employees', postgresql_using='gin', postgresql_ops={'last_name': 'gin_trgm_ops', 'first_name': 'gin_trgm_ops', 'middle_name': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_employees_first_name'), table_name='employees')
    op.drop_index(op.f('ix_employees_employment_status'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_positions_title'), table_name='positions')
    op.drop_index(op.f('ix_positions_department_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_roles_code'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
